### PR TITLE
[WIP] DTOs

### PR DESCRIPTION
**Pull request by johannesschobel**
# PLEASE DO NOT MERGE THIS PR YET

For now, this PR reverts most of the `don't use Requests anymore` commit from this week.

Furthermore, some smaller changes are introduced:
- added a few type-hints for methods, 
- cleaned up config files
- styling
- added some minor actions / tasks

### CODE REVIEW

**Comment by deviouspk** [comment]
why change [] to array() ?

**Comment by johannesschobel** [comment]
because it is more "laravelish" to use `[]` instead of `array()`

**Comment by Kyslik** [comment]
Mind sharing "not use requests" issue?

**Comment by johannesschobel** [comment]
Hey @Kyslik ,

problem is, that `Requests` that are passed to `Actions` make `Apiato` quite hard to test (e.g., in order to test an `Action` you need to "fake" a `Request` object and then pass it to the action and so on.. An additional issue is, that - if you write `CLI` (e.g., simple commands) hinders re-usability of already existing code..

Therefore, @Mahmoudz and me decided to switch so `Transporters` (basically some kind of `DTOs`) which hold the `Request` data.

# Don't worry

Although this seems - at first - like an ultimatively breaking change, it is actually not ;) My current `DTO` implementation (see this PR and the one in `apiato/core`) is minimal-invasive, because it actually "transforms" the `Request` to a `Transporter` object.

This is - however - only done, if you explicitly type-hint the param as `Transporter` in your `Action::run()` method.. If you leave it as `Request`, nothing change for you..

I will post an extensive article in the docs, how to properly use this feature, once it is merged.. I am fairly happy with the current implementation, because it requires you to **not even change one single line of code** if you don't want to use `Transporters`, but rather stick to your current approach (e.g., passing `Requests`).

**Pull request merged**
