### PR TITLE
Fix namespace naming

### PR DESCRIPTION
**Pull request by nasrulhazim**
This PR refer to issue #189 .

What it does basically to rename application namespace properly since naming convention used in [apiato/config/app.php](https://github.com/apiato/apiato/blob/master/config/app.php) and [apiato/bootstrap/app.php](https://github.com/apiato/apiato/blob/master/bootstrap/app.php) is not a standard namespaces used in Laravel default setup.

### CODE REVIEW

**Comment by johannesschobel** [comment]
Hey, i think it would be better to include this command in the ship. Otherwise we would have a (nearly) empty container with no purpose..
What do you think?!

**Comment by nasrulhazim** [comment]
I think it's better in a ship. 

But I just started use and exploring apiato today. 

So might need some times to migrate the command from container to the ship (i've tried to do it in a ship, but seems I missed out something, causing the command not properly loaded.)

I'll give another try on weekend to migrate the command from container to ship.

**Comment by johannesschobel** [comment]
Basically, for the Ship you Just need to make a `Commands` folder and put it there.. And you should be ready ;) At least that is, what i think..

In my opinion, this command should go to the Ship, as it is not a container (and, therefore, does not belong there). However, maybe @Mahmoudz can give feedback, where he would like to apply this command!?

If you would put it to the ship, you could also remove the composer file as it is not needed ;)

**Comment by nasrulhazim** [comment]
I've tried moved the `Commands` directory to the Ship directory, update namespace, remove the `composer.json` file as well, run `composer dumpautoload -o` and try to run the command - now the command is now available. huhu..did i missed out something?

**Comment by johannesschobel** [comment]
Yes, you need to register the command ;)
The commands within `App\Containers\*\UI\CLI\...` are automatically added by the framework.. However, `Commands` within the `Ship` are not (as the developer should not place his `Commands` there).

Take a look at the `App\Ship\Generator\GeneratorServiceProvider`. There is a method that automatically registers all defined commands. You can simply adapt it from there..

**Comment by johannesschobel** [comment]
however, the easy-mode ( :) ) would be to just add your command to the `App\Ship\Engine\Kernels\ShipConsoleKernel`

**Comment by Mahmoudz** [comment]
@nasrulhazim @johannesschobel I've did a little refactoring based on this conversation to simply the process of adding generic commands also I've updated the [command docs](http://apiato.io/D.components/commands/).

Basically now you can just drop the commands classes in the `app/Ship/Commands` folder and they will get automatically registered. 
Alternatively if you want to place them anywhere else for any reason you can use the `app/Ship/Engine/Kernels/ShipConsoleKernel.php` class to register them.
Right now they get auto registered by the `app/Ship/Engine/Loaders/ConsolesLoaderTrait.php`. Unlike the Generator commands which are treated differently since they are more like a portable container this getting registered by their Service Provider `app/Ship/Generator/GeneratorsServiceProvider.php`.

**Comment by johannesschobel** [comment]
i already took a look at the changes - i like it 😄  awesome work!
Cheers 🍺

**Comment by Mahmoudz** [comment]
@johannesschobel thanks for the help man, and thanks to @nasrulhazim for the amazing contributions, hope to see more of you and welcome to the team :)

**Comment by johannesschobel** [comment]
haha, its nice to see that i know enough about apiato that i am able to help other people getting around and contribute ^^

**Comment by nasrulhazim** [comment]
nice one @Mahmoudz ! I'll help to contribute as mush as possible. ^_^

**Pull request merged**
