### PR TITLE
Filter Transformers

### PR DESCRIPTION
**Pull request by johannesschobel**
This update updates the transformer when requesting an endpoint with `?filter=name;email;x` parameters.
Thereby, all "unwanted" fields are removed from the resultset.

Works with all currently provided Serializers (DataArraySerializer, JsonApiSerializer, ...)

This fixes issue #140 .

### CODE REVIEW

**Comment by gajicm93** [comment]
How to specify fields from fields for embedded relationship objects?

Since this transformer also removes all omitted fields from embedded objects, this makes this completely useless for requests that have embedded objects..

So, how to specify filters for embedded objects, and I also need option to specify WHICH embedded objects to return, I don't need all of them.

**Comment by johannesschobel** [comment]
what do you mean with "embedded" objects? objects that are added via `?include` or as `defaultIncludes`?

**Comment by gajicm93** [comment]
The documentation states "This also applies for all (!) relationships (i.e., includes) of the object.".

This is the problem. I need to be able to specify fields for relationships (includes), otherwise this is a useless feature..

**Comment by johannesschobel** [comment]
it is not useless.. it may be useless for you - that is different..

the problem is, that you are not able to "intercept" the "transformation" process of the transformers. So you only get the "fully transformed" array back - this array, in turn, then includes all the `includes`. 

Furthermore, this **must** be done right after the array-transformation, because otherwise different "serializers" are applied (e.g., `JsonApiSerializer`). These serializers, in turn, modify the transformed array to a specific format (e.g,. according to the `Json Api Specs`).

You are free to change / override the `transform()` method to your needs (e.g., remove this feature completely)

**Comment by gajicm93** [comment]
I'll use an example from the docs:

`api.domain.dev/endpoint?filter=id;status`

returns..

```
{
  "data": [
    {
      "id": "0one37vjk49rp5ym",
      "status": "approved",
      "products": {
        "data": [
          {
            "id": "bmo7y84xpgeza06k",
            "status": "pending"
          },
          {
            "id": "o0wzxbg0q4k7jp9d",
            "status": "fulfilled"
          }
        ]
      },
      "recipients": {
        "data": [
          {
            "id": "r6lbekg8rv5ozyad"
          }
        ]
      },
      "store": {
        "data": {
          "id": "r6lbekg8rv5ozyad"
        }
      }
    }...
```

The problem is that "filter=id;status" also removes everything other than id and status from "product" object also. What if I need a e.g. "product_name" field in the product object, which doesn't also exist in the original "endpoint" model. How do I make a query like this?

I think that I currently can't, which makes filtering useless for any use case where you need additional fields in the relationship models, in comparison to original "endpoint" model..

How do I do this? And also, how do I specify the query not to return "recipients" and "store" models, cause I don't need them?

**Comment by gajicm93** [comment]
I should be able to write something like:

api.domain.dev/endpoint?filter=id;status;**product.name**

But I can't.. And you're missing this very important feature.

Facebook Graph API supports this with the following syntax:

`GET graph.facebook.com/me?fields=albums.limit(5){name, photos.limit(2)},posts.limit(5)`

So in our case it should look something like this:

`api.domain.dev/endpoint?filter=id;status;products{id, name}`

But you don't support this, and for that reason I CAN'T use filtering, even though I WANT to..

You can read more here: https://developers.facebook.com/docs/graph-api/using-graph-api/

**Comment by johannesschobel** [comment]
I don't think that the Facebook URI scheme is good at all, but this is another thing..

The problem with the includes is, that you don't know, WHICH fields of the transformer are "just plain nested objects" and which ones are "includes". Therefore this is not possible.

However, just don't use the filter feature if this does not work in your specific application scenario..

Again, just because it does but suite YOUR specific scenario, this feature is not useless..

**Comment by johannesschobel** [comment]
Oh.. and BTW, you realize that the Facebook API is managed by 100+ devs, this framework here is maintained by 1-3 people... 

Just to mention this..

**Comment by gajicm93** [comment]
Yeah I'm aware how many devs that have, but you also gotta admit that this "filter" feature is only partially implemented, and only for a small subset of use cases, essentially it's great only if you don't have any "includes" objects, otherwise you're missing a lot of the necessary customization.

In theory, there are 2 big use cases it currently can't handle:
1. When I need MORE fields in the "includes" objects than in the "endpoint" object.
2. When I need LESS fields in the "includes". For example, I need "id" for the "endpoint" object, but I don't need it for the "products" object.

I'm not a REST/backend developer, I'm just an Android developer forced to work with an API based on your framework, but if I were a backend dev, a missing feature like this would be one of the reasons against using your framework.

Keep this in mind as a feature request for when you have some free dev time.

Cheers.

**Comment by johannesschobel** [comment]
best thing one could achieve would be to have something like this:
`users?filter=firstname,lastname,role.name`

Using `{` or `(` in the URL as facebook does it is really weird..

If i have some time left, i can look at this.. however, this may take some time!

**Comment by gajicm93** [comment]
Exactly! Thanks. This would mean a world for anything more than the most basic use cases..

**Comment by johannesschobel** [comment]
however, i would suggest to not use `?filter=...` in your case... at least for the moment..

**Comment by gajicm93** [comment]
Well right now I literally **can't**. Even though I want to. Because I can't make it return everything I need in the "product" model. Hence why this whole conversation. 😃

**Pull request merged**
