### PR TITLE
Update migration level position

### PR DESCRIPTION
**Pull request by Kyslik**
OCD steps in... Just so timestamps are in the end.

### CODE REVIEW

**Comment by johannesschobel** [comment]
not sure about this PR... because, actually i don't know, if `after` is supported by all databases (e.g., i think, MSSQL does not).. Furthermore - it only "reorders" the columns on database-level..
If one would start reordering it here, you most likely would need to "refactor" all migration files.. and there is no real benefit - besides you have the "timestamp" values at the end..

**Comment by Kyslik** [comment]
Official [database support](https://laravel.com/docs/5.5/database#introduction):

- MySQL
- PostgreSQL
- SQLite
- SQL Server

Yes it does re-order columns **only** (thus OCD comment) when creating it (database-level). And timestamps are not at the end column `level` is.

This is not a major thing since every user can change it :) its not in "core" package, just a stub.

**Comment by johannesschobel** [comment]
yes, but the docs also states [here](https://laravel.com/docs/5.5/migrations#creating-columns) (section "Column Modifiers"):

> `->after('column')`: Place the column "after" another column (MySQL)

Although Laravel supports different databases, not the entire "syntax" is compatible amongst those database engines! And that is, what i meant - i believe that `after` is not supported by different engines, like `truncate`, for example, does also not work on various database engines, because it is some kind of "mysql specific syntax" that they once added to the SQL syntax..

**Comment by Kyslik** [comment]
True that! My bad.

**Comment by johannesschobel** [comment]
sorry for that 😢

**Pull request closed without merging**
