### PR TITLE
Feature/disable pagination

### PR DESCRIPTION
**Pull request by johannesschobel**
This fix lets requestors disable pagination by simply adding `?limit=0` to the URL. Otherwise it is not possible to circumvent a paginated resultset, if the dev used return `$repository->paginate()`.
The feature can now be turned on/off in every repository (**turned off by default**) by setting the `$allowDisablePagination` variable respectively.

This can be handy, if a full-blown client with stable and broadband connection would like to fetch all data. Mobile clients, however, would still get a paginated result!

----------

Furthermore, I have changed the `PAGINATION_LIMIT` ENV variable to `PAGINATION_LIMIT_DEFAULT` in order to clarify its purpose.

---------

Finally, I have updated the `docs` as well as the `Documentation` container in order to reflect my changes (e.g., added the `?limit` parameter and fixed a few typos!)

Cheers

### CODE REVIEW

**Comment by johannesschobel** [comment]
i don't know, why it shows the `.env.example` file as conflicted.. ;) but anyways.. here is my PR

**Comment by Mahmoudz** [comment]
I've added `PAGINATION_SKIP` to control that feature from the `.env` file 716a0b9d48d7c95cffdce1c92a02910932a60bb2.

**Comment by envision** [comment]
How about if there indeed would be like over 10k records. Should there still be some limit? Otherwise such endpoint would be prime entry for a Denial of Service attacks?

Or actually that _pagination skip_ setting should perhaps be resource specific?

**Comment by johannesschobel** [comment]
@envision remember that you can control how many requests a user can make!

**Comment by johannesschobel** [comment]
hmmm... as i think about it.. wouldn't it be better to combine both approaches?
1) The overall ENV setting to activate / deactive the feature
2) A flag for each repository to enable / disable it on repository level?

**Pull request merged**
