### PR TITLE
update pusher env variables to be compatible with config

### PR DESCRIPTION
**Pull request by deviouspk**
Makes the env variables for pusher compatible with the ones defined in the broadcasting config file

### CODE REVIEW

**Comment by johannesschobel** [comment]
Will review this tomorrow and give feedback :) thank your for contributing

**Comment by Mahmoudz** [comment]
@deviouspk thanks for the fix, @johannesschobel I checked it it's valid.

**Comment by johannesschobel** [comment]
Haha, ok ;)

**Comment by deviouspk** [comment]
noproblem :)

**Pull request merged**
