### PR TITLE
Add Apiato facade to ShipProvider

### PR DESCRIPTION
**Pull request by DomasWEB**
## Description
Apiato facade alias was not registered anywhere in the application and when using barryvdh/laravel-ide-helper it does not recognise this alias as registered and does not give autocompletion for IDEA applications (PHPStorm for example).

## Motivation and Context
For autocompletion on IDE's

## How Has This Been Tested?
No tests required

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style and structure of this project.

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@DomasWEB the facade is registered in the core [here](https://github.com/apiato/core/blob/master/Providers/ApiatoProvider.php#L97).
Maybe you have a problem with it cause you're not requiring apiato/core 2.0! try running composer update to get that version. If that wasn't the problem, let me know. Thanks

**Comment by DomasWEB** [comment]
I am running the latest dev-master of apiato/core.

I can confirm that I see that code there but ide-helper but https://github.com/barryvdh/laravel-ide-helper does not pick it up in the facade generation.

What could be the solution to let ide-helper know of this facade?

Thank you

**Comment by Mahmoudz** [comment]
Don't know much about that package. But if adding that facade on your side didn't affect anything, you can have it as workaround but shouldn't be part of the project since it will be duplicated.

**Comment by hfengshan** [comment]
you should write comment at Apiato\Core\Foundation\Facades\Apiato like that 
"@method static mixed call(string $class, array $runMethodArguments = [], array $extraMethodsToCall = [])"

**Pull request closed without merging**
