### PR TITLE
Fixed error in QueryDebugger when bindings were DateTime objects or boolean values

### PR DESCRIPTION
**Pull request by jlorente**
## Description
The QueryDebugger object was throwing an error "Object of class DateTime could not be converted to string" when a DateTime object was been set as binding of a Query.

## Motivation and Context
With this Pull Request, the QueryDebugger is handling the bindings the same way as the Connection::prepareBindings(array $bindings) does.

## How Has This Been Tested?
With phpunit and the QUERIES_DEBUG environment variable set to true.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style and structure of this project.
- [] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by johannesschobel** [comment]
Hey there, thanks for your contribution. I am not sure, if i understand the issue correctly. Can you provide a simple example that fails? ;) Maybe this helps me to see the actual issue? ;)
Thank you very much and kind regards

**Comment by jlorente** [comment]
Ok, here it goes.

Laravel allows to pass a DateTime object or a boolean as binding value of a Query.

 For example like this.
```php
    /**
     * @group CustomTest
     */
    public function testOne()
    {
        $repository = App::make(SomeRepository::class)->create([
            'datetime_at' => new DateTime
            , 'my_bool' => false
        ]);
    }
```
This is handled in the Connection::prepareBindings method.

vendor/laravel/framework/src/Illuminate/Database/Connection.php
```php
    /**
     * Prepare the query bindings for execution.
     *
     * @param  array  $bindings
     * @return array
     */
    public function prepareBindings(array $bindings)
    {
        $grammar = $this->getQueryGrammar();

        foreach ($bindings as $key => $value) {
            // We need to transform all instances of DateTimeInterface into the actual
            // date string. Each query grammar maintains its own date string format
            // so we'll just ask the grammar for the format to get from the date.
            if ($value instanceof DateTimeInterface) {
                $bindings[$key] = $value->format($grammar->getDateFormat());
            } elseif (is_bool($value)) {
                $bindings[$key] = (int) $value;
            }
        }

        return $bindings;
    }
```

Now, the bindings passed in the QueryExecuted event are the raw bindings, so the attributes received in the QueryDebugger class are, in this case, the DateTime object and the boolean value. When using this array of attributes in the *vsprintf* function, the application throws a "Object of class DateTime could not be converted to string" error.

This Pull Request makes the QueryDebugger handle the bindings array the same way as the prepareBindings method.

**Comment by johannesschobel** [comment]
Am I correct, that this only affects the `Debugger` - e.g., if you dump all executed Query Statements? In "production mode" (when this flag is turned off), this does not occur?!

**Comment by jlorente** [comment]
Yes, this only affects the Debugger.

**Pull request merged**
