### PR TITLE
Add an Artisan command to generate Swagger/OpenAPI JSON schema from apiDoc

### PR DESCRIPTION
**Pull request by mertyildiran**
## Description
This PR adds an Artisan command to Documentation container for generating Swagger/OpenAPI JSON schema from apiDoc. It primarily calls https://github.com/fsbahman/apidoc-swagger to do the conversion. But it does not provide a Swagger UI out of the box. You have to copy & paste the JSON into https://editor.swagger.io/

Closes https://github.com/apiato/apiato/issues/90

## Motivation and Context
I needed to have the API documentation in Swagger/OpenAPI format rather than apiDoc because I wanted to generate the client-side code using a generator like [this one](https://github.com/api-platform/client-generator) and it requires to have an OpenAPI definition. So I wrote a command like this:

```
apidoc-swagger -v -f '.*\.php$' -i ./app -o ./public/api/private/swagger/
```

to have the JSON schema. Then I decided to turn that into an official Apiato Artisan command. Hope it finds you well.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Definition of Done Checklist:

- [x] My code follows the code style and structure of this project.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Mohammad-Alavi** [comment]
Hi @mertyildiran 

I have been trying to make your PR work and generate swagger json with no success. There are other people having the same problem and i think we are all using Windows. I saw someone using Laragon generated docs without any problems.

Here is the error 
```
  The command ""node_modules/.bin/apidoc-swagger" -v "" -f '.*\.php$' -i app -o "public/api/documentation/swagger"" failed.  
                                                                                                                             
  Exit Code: 1(General error)                                                                                                
                                                                                                                             
  Working directory: C:\Users\moham\PhpstormProjects\beskoot                                                                 
                                                                                                                             
  Output:                                                                                                                    
  ================                                                                                                           
  verbose: apidoc-generator name: apidoc-swagger                                                                   
  verbose: apidoc-generator version: 0.3.2                                                                         
  verbose: apidoc-core version: 0.11.0                                                                             
  verbose: apidoc-spec version: 0.3.0                                                                              
  verbose: run parser                                                                                              
                                                                                                                             
                                                                                                                             
  Error Output:                                                                                                              
  ================                                                                                                           
  error: No files found.                                                                                           
  { Path: 'C:\\Users\\moham\\PhpstormProjects\\beskoot' }     
```

Have you any idea how we can fix this?

**Comment by mertyildiran** [comment]
@Mohammad-Alavi Just try to run 
```
apidoc-swagger -v -f '.*\.php$' -i ./app -o ./public/api/private/swagger/
``` 
make sure your apiDoc commented PHP files exists inside `./app` directory. If you are targeting some other directory then specify that path instead of `./app`. If you're still getting an error the issue is totally related to https://github.com/fsbahman/apidoc-swagger because this Artisan command is just a simple wrapper around that shell command to standardize the process.

See this [yet to be merged PR](https://github.com/fsbahman/apidoc-swagger/pull/53/files) of mine, to check if there are any relevance. Unfortunately, [apidoc-swagger](https://github.com/fsbahman/apidoc-swagger) is a pretty inactive repository...

**Comment by Mohammad-Alavi** [comment]
@mertyildiran Thanks for the quick answer.

Now i get this error:
`
error: Cannot read property 'indexOf' of undefined
`

**Comment by mertyildiran** [comment]
@Mohammad-Alavi again, if that error is coming from `apidoc-swagger` then the issue is related to https://github.com/fsbahman/apidoc-swagger or your apiDoc comment blocks have some problems.

**Comment by Mohammad-Alavi** [comment]
Oh with the new command you provided and the fixes in your PR it worked !@_@!

**Comment by Mohammad-Alavi** [comment]
@mertyildiran This command works fine when used directly in command line but not when used through Apiato task (with the fixes in [your PR](https://github.com/fsbahman/apidoc-swagger/pull/53/files)).
`apidoc-swagger -v -f '.*\.php$' -i ./app -o ./public/api/private/swagger/swagger.json`
Do you have any suggestions?

**Comment by Mohammad-Alavi** [comment]
The problem was using "" instead of '' in Apiato task.

**Comment by mertyildiran** [comment]
@Mohammad-Alavi because this Artisan command uses `node_modules/.bin/apidoc-swagger` instead of your global `apidoc-swagger` [see](https://github.com/apiato/apiato/pull/536/files#diff-4b2bd7897597a164671d3b7846888b0aR25). So in this case I would suggest you to publish a new `npm` package by forking [apidoc-swagger](https://github.com/fsbahman/apidoc-swagger) and applying the [patch](https://github.com/fsbahman/apidoc-swagger/pull/53/files), since the maintainer seems inactive.

**Comment by Mohammad-Alavi** [comment]
> @Mohammad-Alavi because this Artisan command uses `node_modules/.bin/apidoc-swagger` instead of your global `apidoc-swagger` [see](https://github.com/apiato/apiato/pull/536/files#diff-4b2bd7897597a164671d3b7846888b0aR25). So in this case I would suggest you to publish a new `npm` package by forking [apidoc-swagger](https://github.com/fsbahman/apidoc-swagger) and applying the [patch](https://github.com/fsbahman/apidoc-swagger/pull/53/files), since the maintainer seems inactive.

Yea i was thinking the same. I'll w8 for a week or so and then if the maintainer didn't merge your PR i'll do it as you suggested.

**Pull request merged**
