### PR TITLE
Add WebLocalizationMiddleware for web routes instead api middleware

### PR DESCRIPTION
**Pull request by dmekhov**
For web routes we can use WebLocalizationMiddleware - which sets the default language in `Content-Language` response header, instead of throwing an exception.

## Description
I'm add WebLocalizationMiddleware and use it instead  LocalizationMiddleware in MiddlewareServiceProvider.
Also I'm move private methods from LocalizationMiddleware to LocalizationTrait - for using them in the future, in WebLocalizationMiddleware if you want to use url segments for detect locale (you can want validate locale for example).

## Motivation and Context
This is necessary for cases when a user call a web routes, in a browser that sends the Accept-Language header but which is not included in the list of supported.
Now the user sees an error page, but must see the page default language - unless otherwise specified.
(This PR is associated with https://github.com/apiato/apiato/pull/439)

## How Has This Been Tested?
Test for WebLocalizationMiddleware was added.
Now I don't see `makeCall` helper for web routes, so I use standart call method in tests.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style and structure of this project.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dmekhov** [comment]
@johannesschobel, what do you think about this?

**Comment by johannesschobel** [comment]
Hey @dmekhov , sorry for the long response-time on this.. Been very busy lately..

I don't think, that this is appropriate, because of the following reasons:
1) I think, the `WebLocalizationMiddleware` should validate the localization that is passed in the URL! However, bear in mind, that the url schema must be customizable (e.g., it may be `http://www.example.com/en/...` or `http://www.example.com/v1/en/...`).
2) you are moving functions to traits and then are not using the latter in the `WebLocalizationMiddleware`

What do you think?

**Comment by dmekhov** [comment]
Yes, but i don't shure about version segment in web routes. And much more difficult to have several optional segments..

I added route group with lang segment in apiato/core (https://github.com/apiato/core/pull/106) and lang detection in web-middleware (https://github.com/apiato/apiato/pull/440/commits/b08ec5d4a381c19ca82d32f4553348283d3880be).   

If all is right and when core will be updated - I will update tests for this PR.

**Comment by dmekhov** [comment]
I'm add `use_localized_routes` config flag.
And add overridden route helper - but for load this before laravel helpers I add this to `public/index.php` - if you have better solution - i will use it.
Also this solution don't work in tests  - phpunit.xml use vendor/autoload.php and dont read index.php, how i can say phpunit use app helpers first?

And also where i can define root route redirect logic - so that the prefix rules do not apply to it? 
Now if I add redirect rule to container route - it get prefix from core loader (with true flag).

**Pull request closed without merging**
