### PR TITLE
Taking out dingo jwt replace with passport & fractal

### PR DESCRIPTION
**Pull request by wouterNL**

### CODE REVIEW

**Comment by Mahmoudz** [comment]
@wouterNL Hi Thanks for this PR, I left some comments, please review them try to solve the conflict. After that I'll try to run it on my machine to see how it works.. best,

**Comment by wouterNL** [comment]
Done.

**Comment by Mahmoudz** [comment]
@wouterNL looks cool, I just created a branch to test that, was fixing the conflicts.. however I'm still not able to run my tests successfully. But I'll do everything in public inside that branch so you can also have a look and help me switch to passport..

**Comment by Mahmoudz** [comment]
@wouterNL just a question, have you run the tests 17 days ago! when you said it's Done? If yes you probably missing some commits! I can see the `jwtAuthAdapter` is still being used for authentication, while it's not there anymore! I wonder how it's works!, any help?

**Comment by wouterNL** [comment]
I left all the old jwt in there, it's no longer used, I just wanted to get Passport in there. 
I am no longer able to really help or fix anything on this branch since I am really busy with personal/work projects.

**Comment by Mahmoudz** [comment]
@wouterNL no problem I totally understand and appreciate your efforts.. I'm working on that right now. I'm getting more errors than I expected I hope I don't waste my weekend on this :P

**Comment by wouterNL** [comment]
Haha, yeah I never fixed the tests, had no time for it. Sorry 'bout that.

On Mar 31, 2017, at 3:18 PM, Mahmoud Zalt <notifications@github.com<mailto:notifications@github.com>> wrote:


@wouterNL<https://github.com/wouterNL> no problem I totally understand and appreciate your efforts.. I'm working on that right now. I'm getting more errors than I expected I hope I don't waste my weekend on this :P

**Pull request merged**
